version: '2'

networks:
  kafka:
    name: spring-kafka-streams-demo

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
    networks:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    networks:
      - kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_HOST://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - kafka
    ports:
      - 8081:8081
    networks:
      - kafka
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'kafka:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  kafka-init:
    image: confluentinc/cp-kafka
    hostname: kafka-init
    container_name: kafka-init
    depends_on:
      - zookeeper
      - kafka
    networks:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      echo '-----------'
      # blocks until kafka is reachable
      echo 'Topics before:'
      kafka-topics --bootstrap-server kafka:29092 --list

      echo ''
      echo 'Creating kafka topics...'
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic topic-a --replication-factor 1 --partitions 1
      kafka-topics --bootstrap-server kafka:29092 --create --if-not-exists --topic topic-b --replication-factor 1 --partitions 1

      echo ''
      echo 'Topics after:'
      kafka-topics --bootstrap-server kafka:29092 --list
      "